# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-31 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('desc', models.CharField(max_length=150, verbose_name='描述')),
                ('manager', models.CharField(max_length=100, verbose_name='板块管理员')),
            ],
        ),
    ]
